# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M1K18uYSCkQAZhnG4yo7Eah33wiNVhjQ
"""

import matplotlib.pyplot as plt
import numpy as np
from numpy import *
from math import *
import sympy as sm
print("please input the range of f(x) in [a,b]")
a=input('a:')
b=input('b:')
a=int(a)
b=int(b)
x = np.linspace(a,b,1000)
a=input("f(x)= ")
def f(x): return  eval(a)    #####function to graph
plt.figure(1)
txt=sm.symbols('f(x)')
txt2=s.symbols("f'(x)")
plt.plot(x,f(x))
plt.axhline(color='black')
plt.axvline(color='black')
############################Differntiate of f(x)########################
def round_to_1(x):
  return round(x, -int(floor(log10(abs(x)))))
def fprime(x):
  dx=1/100
  return ((f(x+dx)-f(x))/dx)
################################################Graph tHE Derivative#############################################

plt.figure(2)
print("Graph of f'(x)")
plt.plot(x,fprime(x))
plt.axhline(color='black')
plt.axvline(color='black')

txt


###########################################By Hasan Saleh #############################################x